// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DataClearCompleted() {
  return window['go']['app']['App']['DataClearCompleted']();
}

export function DataExport() {
  return window['go']['app']['App']['DataExport']();
}

export function DataImport(arg1) {
  return window['go']['app']['App']['DataImport'](arg1);
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function SettingsGet() {
  return window['go']['app']['App']['SettingsGet']();
}

export function SettingsUpdate(arg1) {
  return window['go']['app']['App']['SettingsUpdate'](arg1);
}

export function TaskCreate(arg1) {
  return window['go']['app']['App']['TaskCreate'](arg1);
}

export function TaskDelete(arg1) {
  return window['go']['app']['App']['TaskDelete'](arg1);
}

export function TaskGet(arg1) {
  return window['go']['app']['App']['TaskGet'](arg1);
}

export function TaskList(arg1, arg2) {
  return window['go']['app']['App']['TaskList'](arg1, arg2);
}

export function TaskToggleCompleted(arg1) {
  return window['go']['app']['App']['TaskToggleCompleted'](arg1);
}

export function TaskTogglePause(arg1) {
  return window['go']['app']['App']['TaskTogglePause'](arg1);
}

export function TaskUpdate(arg1) {
  return window['go']['app']['App']['TaskUpdate'](arg1);
}

export function WorkspaceCreate(arg1) {
  return window['go']['app']['App']['WorkspaceCreate'](arg1);
}

export function WorkspaceDelete(arg1) {
  return window['go']['app']['App']['WorkspaceDelete'](arg1);
}

export function WorkspaceList() {
  return window['go']['app']['App']['WorkspaceList']();
}

export function WorkspaceUpdate(arg1) {
  return window['go']['app']['App']['WorkspaceUpdate'](arg1);
}
