// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {requests} from '../models';
import {models} from '../models';

export function DataClearCompleted():Promise<void>;

export function DataExport():Promise<string>;

export function DataImport(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function SettingsGet():Promise<Record<string, string>>;

export function SettingsUpdate(arg1:requests.SettingsUpdateReq):Promise<void>;

export function TaskCreate(arg1:requests.TaskCreateReq):Promise<models.Task>;

export function TaskDelete(arg1:number):Promise<void>;

export function TaskGet(arg1:number):Promise<models.Task>;

export function TaskList(arg1:number,arg2:string):Promise<Array<models.Task>>;

export function TaskToggleCompleted(arg1:number):Promise<models.Task>;

export function TaskTogglePause(arg1:number):Promise<models.Task>;

export function TaskUpdate(arg1:requests.TaskUpdateReq):Promise<models.Task>;

export function WorkspaceCreate(arg1:requests.WorkspaceCreateReq):Promise<models.Workspace>;

export function WorkspaceDelete(arg1:number):Promise<void>;

export function WorkspaceList():Promise<Array<models.Workspace>>;

export function WorkspaceUpdate(arg1:requests.WorkspaceUpdateReq):Promise<models.Workspace>;
